import "./globals.css";
import "@repo/ui/styles.css";
import Wrapper from "@repo/ui/Wrapper";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
  openGraph: {
    title: "Quizzify",
    siteName: "Quizzify",
    url: "https://quizzify-green.vercel.app/",
    description:
      "Enter any topic and get instant, personalized quizzes to enhance your learning. Receive detailed analytics and curated resources to fill knowledge gaps.",
    type: "website",
    images: [
      {
        url: "https://quizzify-green.vercel.app/Quizzify.png",
        width: 1200,
        height: 630,
        alt: "Quizzify Cover Image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Quizzify",
    description:
      "Enter any topic and get instant, personalized quizzes to enhance your learning. Receive detailed analytics and curated resources to fill knowledge gaps.",
    images: ["https://quizzify-green.vercel.app/Quizzify.png"],
    creator: "@AtulGoyal383989"
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
