import "./globals.css";
import "@repo/ui/styles.css";
import Wrapper from "@repo/ui/Wrapper";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
